<?php

$pluginInfo = osc_plugin_get_info('seo_plugin/index.php');

?>

<div id="settings_form">
  <?php echo config_menu();?>

  
  <fieldset>
    <legend><i class="fa fa-cog"></i>&nbsp;<?php _e('Seo plugin description', 'seo_plugin'); ?></legend>
    <ul style="list-style-type: square;">
	<strong><?php _e('Custom keywords', 'seo_plugin'); ?></strong>
	<li><?php _e('If you enable custom keywords, they will be added to keywords they are generated by categories, listings and static pages.', 'seo_plugin'); ?></li>
	<li><?php _e('Delimiter is used in every meta title', 'seo_plugin'); ?></li>
	    <br />
    <strong><?php _e('Listings', 'seo_plugin'); ?></strong>
    <li><?php _e('In this section you can configure the ad title. Selects whether to show it in the category, city, region, country and site name.', 'seo_plugin'); ?></li>
    <li><?php _e('You can choose one or more functions. It also set the sequence of their output.', 'seo_plugin'); ?></li>
    <br />
	
    <strong><?php _e('Categories', 'seo_plugin'); ?></strong>
    <li><?php _e('In this section you can configure the title, description and keywords for each category', 'seo_plugin'); ?></li>

    <br />

    <strong><?php _e('Regions', 'seo_plugin'); ?></strong>
    <li><?php _e('In this section you can configure the title, description and keywords for the regions', 'seo_plugin'); ?></li>
    <li><?php _e('Print the title on the site will be as follows: Name of the current region - title that you entered', 'seo_plugin'); ?> </li>
    <li><?php _e('Similarly, description will be displayed and keywords (in this parameter will be used a comma after the name of the region)', 'seo_plugin'); ?></li>
    <li><?php _e('All enter keywords separated by commas', 'seo_plugin'); ?></li>

    <br />
	<strong><?php _e('Cities', 'seo_plugin'); ?></strong>
    <li><?php _e('In this section you can configure the title, description and keywords for cities', 'seo_plugin'); ?></li>
    <li><?php _e('Print the title on the site will be as follows: Name of the current city - title that you entered', 'seo_plugin'); ?> </li>
    <li><?php _e('Similarly, description will be displayed and keywords (in this parameter will sipolzovatsya comma after the city name)', 'seo_plugin'); ?></li>
    <li><?php _e('All enter keywords separated by commas', 'seo_plugin'); ?></li>

    <br />

	<strong><?php _e('Home page', 'seo_plugin'); ?></strong>
    <li><?php _e('In this section you can configure the title, description and keywords for the home page', 'seo_plugin'); ?></li>
	 <br />
    <strong><?php _e('Static Pages', 'seo_plugin'); ?></strong>
    <li><?php _e('In this section you can configure the title, description and keywords for each static page', 'seo_plugin'); ?></li>

	<br />
	 <strong><?php _e('Sitemap', 'seo_plugin'); ?></strong>
	 <li><?php _e('You can generate a sitemap.xml, keep pressing Save', 'seo_plugin'); ?></li>
	 <li><?php _e('You can customize the generation schedule: once a week, hour or day. Please note this should be allowed to run the built-cron (Settings - Main - Settings Cron - Allow to run automatically)', 'seo_plugin'); ?></li>
	 <li><?php _e('After each generation of sitemap, a request is sent to<strong>Yandex</strong>, <strong>Google</strong> and <strong>Bing</strong>, search engines reported that sitemap changed and they can quickly index new or changed pages', 'seo_plugin'); ?></li>
     <br />
	<strong><?php _e('Update and reinstall', 'seo_plugin'); ?></strong>
	 <li><?php _e('When you update just replace the files via FTP', 'seo_plugin'); ?></li>
   
    </ul>
  </fieldset>

  <br /><br />

</div>


<?php echo $pluginInfo['version'] . '|  &copy; ' . date('Y') . ' <a href="' . $pluginInfo['plugin_uri'] . '" target="_blank">SEO Plugin</a>'; ?>             
